# Generated by Django 4.0.1 on 2022-01-10 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('header', models.ImageField(upload_to='header', verbose_name='作者头像')),
            ],
            options={
                'verbose_name': '作者基本信息',
                'verbose_name_plural': '作者基本信息',
                'db_table': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Publishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='出版社名称')),
                ('address', models.CharField(max_length=20, verbose_name='出版社地址')),
            ],
            options={
                'verbose_name': '出版社信息',
                'verbose_name_plural': '出版社信息',
                'db_table': 'Publishing',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='图书名称')),
                ('desc', models.TextField(verbose_name='图书描述')),
                ('publishdate', models.DateField(verbose_name='出版日期')),
                ('author', models.ManyToManyField(to='book.AuthorInfo', verbose_name='作者')),
                ('publishing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.publishing', verbose_name='出版商')),
            ],
            options={
                'verbose_name': '图书信息',
                'verbose_name_plural': '图书信息',
                'db_table': 'Book',
            },
        ),
    ]
