# Generated by Django 3.2.10 on 2022-01-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='姓名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
            ],
        ),
    ]
